### ISSUE TITLE
Target and Source Mixed Up

### ISSUE THREAD

**Issue by boesiii** [MSBilgin/Geometry-Updater#2]
Hello.  I think your plugin is great but I think the Target layer and Source layer are mixed up because to me they are backwards.  IMO, the "Source" layer features should be moved to the "Target" layer features.  Maybe you should consider adding some text to the "Target" window outlines, something like "These points will be moved to the source layer"

**Comment by MSBilgin** [comment]
That is really strange because my algorithm changes target layer's features from source layer. You wrote 'Source" layer features should be moved to the "Target" layer features' is correct for this . I dont see any difference... 
Mehmet Selim BILGINJeoloji Muhendisi, CBS UzmaniBaskent Dogalgaz Dagitim A.S.e-mail:   mselimbilgin@yahoo.com
web: cbsuygulama.wordpress.com

```
On Friday, March 25, 2016 5:08 PM, boesiii <notifications@github.com> wrote:
```

 Hello. I think your plugin is great but I think the Target layer and Source layer are mixed up because to me they are backwards. IMO, the "Source" layer features should be moved to the "Target" layer features. Maybe you should consider adding some text to the "Target" window outlines, something like "These points will be moved to the source layer"—

**Comment by boesiii** [comment]
What I am seeing is the "Target" layer is moved to the "Source" layer.  Is this your intent?
