### ISSUE TITLE
Work with only selected features

### ISSUE THREAD

**Issue by boesiii** [MSBilgin/Geometry-Updater#4]
I have two large data sets I am using with your plugin.  It would be better for me to do the updating on smaller groups because I need to see what is matching and what is not.

**Comment by MSBilgin** [comment]
You can do this easily by using [Speedy Layer](https://cbsuygulama.wordpress.com/2016/04/16/speedy-layer-usage/) my another plugin. Firtsly select some features and copy them to memory layer by Speedy Layer and then check results. Also this plugin makes your analysis faster because it copies data to RAM that makes dramatic speed increase.
